services:
  - type: web
    name: nasa-ai-oli-api
    runtime: python
    plan: free
    region: oregon
    buildCommand: |
      python -m pip install --upgrade pip setuptools wheel
      pip install --only-binary=:all: -r python/requirements.txt
    startCommand: cd python && uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
      - key: GOOGLE_API_KEY
        sync: false
    healthCheckPath: /
